// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_crms.Data;

#nullable disable

namespace api_crms.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903234502_AddBlockTemplates")]
    partial class AddBlockTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("api_crms.Models.BlockTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("block_template", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Channels")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channels");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DispatchErrors")
                        .HasColumnType("TEXT")
                        .HasColumnName("dispatch_errors");

                    b.Property<int?>("DispatchFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dispatch_failed_count");

                    b.Property<int?>("DispatchSentCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dispatch_sent_count");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("dispatched_at");

                    b.Property<bool>("EmailTerminal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_terminal");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_at");

                    b.Property<string>("ResolvedRecipients")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_recipients");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_type");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TargetEmails")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_emails");

                    b.Property<Guid?>("TargetSegmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_segment_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("campaign", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CampaignChannelContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("CtaText")
                        .HasColumnType("TEXT")
                        .HasColumnName("cta_text");

                    b.Property<string>("CtaUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cta_url");

                    b.Property<bool>("Dismissible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dismissible");

                    b.Property<string>("Heading")
                        .HasColumnType("TEXT")
                        .HasColumnName("heading");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("link_url");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Channel")
                        .IsUnique();

                    b.ToTable("campaign_channel_content", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CampaignEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_event", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CannedReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("canned_reply", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CannedReplyCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("canned_reply_category", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("PlatformCartId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform_cart_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("PlatformCartId")
                        .IsUnique();

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cart_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("cart_item", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("buyer_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("PrimaryContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_contact_id");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryContactId");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<decimal>("LifetimeValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("lifetime_value");

                    b.Property<bool>("MarketingOptOut")
                        .HasColumnType("INTEGER")
                        .HasColumnName("marketing_opt_out");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<decimal?>("SentimentScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("sentiment_score");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("custom_field_definition", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomFieldDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_field_definition_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldDefinitionId");

                    b.ToTable("custom_field_option", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bool_value");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<Guid>("CustomFieldDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_field_definition_id");

                    b.Property<DateTimeOffset?>("DateValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_value");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("number_value");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("option_id");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("text_value");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldDefinitionId");

                    b.HasIndex("OptionId");

                    b.HasIndex("ContactId", "CustomFieldDefinitionId")
                        .IsUnique();

                    b.ToTable("custom_field_value", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.EcommerceSyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FirstEventReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_event_received_at");

                    b.Property<DateTimeOffset?>("LastEventReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_event_received_at");

                    b.HasKey("Id");

                    b.ToTable("ecommerce_sync_status", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.IdentityMatchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_contact_id");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("SourceReferenceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_reference_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateContactId");

                    b.HasIndex("SourceReferenceId");

                    b.ToTable("identity_match_candidate", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<Guid?>("SenderContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_contact_id");

                    b.Property<string>("SenderStaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_staff_id");

                    b.Property<string>("SenderStaffName")
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_staff_name");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_type");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("SenderContactId");

                    b.HasIndex("TicketId", "SentAt");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PlatformOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform_order_id");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("refunded_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("PlatformOrderId")
                        .IsUnique();

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.OrderLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_line_item", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.ProcessedEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId");

                    b.ToTable("processed_event", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("InStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("in_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PlatformProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform_product_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlatformProductId")
                        .IsUnique();

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Rule")
                        .HasColumnType("TEXT")
                        .HasColumnName("rule");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("segment", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.SegmentMembership", b =>
                {
                    b.Property<Guid>("SegmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("segment_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("SegmentId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("segment_membership", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.SourceReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("MatchConfidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("match_confidence");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("SourceSystem", "SourceId")
                        .IsUnique();

                    b.ToTable("source_reference", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("Id");

                    b.HasIndex("Channel");

                    b.ToTable("template", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.TemplateBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockTemplateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("block_template_id");

                    b.Property<bool>("IsBold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_bold");

                    b.Property<bool>("IsItalic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_italic");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<string>("TextAlign")
                        .HasColumnType("TEXT")
                        .HasColumnName("text_align");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("BlockTemplateId");

                    b.ToTable("template_block", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToEmail")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_to_email");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_to_id");

                    b.Property<string>("AssignedToName")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_to_name");

                    b.Property<string>("CanceledBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("canceled_by");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalThreadId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_thread_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WaitingOn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("waiting_on");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("ExternalThreadId");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("WaitingOn");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.TimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_module");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("ContactId", "OccurredAt");

                    b.ToTable("timeline_entry", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("StopCondition")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_condition");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.ToTable("workflow", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_step_index");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("NextStepDueAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_step_due_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("Status", "NextStepDueAt");

                    b.ToTable("workflow_run", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActionConfig")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_config");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<TimeSpan>("WaitDuration")
                        .HasColumnType("TEXT")
                        .HasColumnName("wait_duration");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("workflow_step", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CampaignChannelContent", b =>
                {
                    b.HasOne("api_crms.Models.Campaign", "Campaign")
                        .WithMany("ChannelContents")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("api_crms.Models.CampaignEvent", b =>
                {
                    b.HasOne("api_crms.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("api_crms.Models.CannedReply", b =>
                {
                    b.HasOne("api_crms.Models.CannedReplyCategory", "Category")
                        .WithMany("CannedReplies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("api_crms.Models.Cart", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("Carts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.CartItem", b =>
                {
                    b.HasOne("api_crms.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("api_crms.Models.Company", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "PrimaryContact")
                        .WithMany()
                        .HasForeignKey("PrimaryContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryContact");
                });

            modelBuilder.Entity("api_crms.Models.Contact", b =>
                {
                    b.HasOne("api_crms.Models.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldOption", b =>
                {
                    b.HasOne("api_crms.Models.CustomFieldDefinition", "Definition")
                        .WithMany("Options")
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldValue", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_crms.Models.CustomFieldDefinition", "Definition")
                        .WithMany("Values")
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_crms.Models.CustomFieldOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");

                    b.Navigation("Definition");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("api_crms.Models.IdentityMatchCandidate", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "CandidateContact")
                        .WithMany()
                        .HasForeignKey("CandidateContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api_crms.Models.SourceReference", "SourceReference")
                        .WithMany("IdentityMatchCandidates")
                        .HasForeignKey("SourceReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateContact");

                    b.Navigation("SourceReference");
                });

            modelBuilder.Entity("api_crms.Models.Message", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "SenderContact")
                        .WithMany()
                        .HasForeignKey("SenderContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("api_crms.Models.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenderContact");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("api_crms.Models.Order", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("Orders")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.OrderLineItem", b =>
                {
                    b.HasOne("api_crms.Models.Order", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("api_crms.Models.SegmentMembership", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_crms.Models.Segment", "Segment")
                        .WithMany("Memberships")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("api_crms.Models.SourceReference", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("SourceReferences")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.TemplateBlock", b =>
                {
                    b.HasOne("api_crms.Models.BlockTemplate", "BlockTemplate")
                        .WithMany("Blocks")
                        .HasForeignKey("BlockTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockTemplate");
                });

            modelBuilder.Entity("api_crms.Models.Ticket", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.TimelineEntry", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.WorkflowRun", b =>
                {
                    b.HasOne("api_crms.Models.Workflow", "Workflow")
                        .WithMany("Runs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("api_crms.Models.WorkflowStep", b =>
                {
                    b.HasOne("api_crms.Models.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("api_crms.Models.BlockTemplate", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("api_crms.Models.Campaign", b =>
                {
                    b.Navigation("ChannelContents");
                });

            modelBuilder.Entity("api_crms.Models.CannedReplyCategory", b =>
                {
                    b.Navigation("CannedReplies");
                });

            modelBuilder.Entity("api_crms.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("api_crms.Models.Company", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("api_crms.Models.Contact", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("CustomFieldValues");

                    b.Navigation("Orders");

                    b.Navigation("SourceReferences");

                    b.Navigation("TimelineEntries");
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldDefinition", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("api_crms.Models.Order", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("api_crms.Models.Segment", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("api_crms.Models.SourceReference", b =>
                {
                    b.Navigation("IdentityMatchCandidates");
                });

            modelBuilder.Entity("api_crms.Models.Ticket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("api_crms.Models.Workflow", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
