// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_crms.CustomerIdentity.Persistence;

#nullable disable

namespace api_crms.CustomerIdentity.Persistence.Migrations
{
    [DbContext(typeof(CustomerIdentityDbContext))]
    [Migration("20260825191817_AddIdentityMatchCandidates")]
    partial class AddIdentityMatchCandidates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("api_crms.CustomerIdentity.Persistence.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("api_crms.CustomerIdentity.Persistence.IdentityMatchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateCustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_customer_id");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("SourceReferenceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_reference_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCustomerId");

                    b.HasIndex("SourceReferenceId");

                    b.ToTable("identity_match_candidate", (string)null);
                });

            modelBuilder.Entity("api_crms.CustomerIdentity.Persistence.SourceReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("MatchConfidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("match_confidence");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SourceSystem", "SourceId")
                        .IsUnique();

                    b.ToTable("source_reference", (string)null);
                });

            modelBuilder.Entity("api_crms.CustomerIdentity.Persistence.IdentityMatchCandidate", b =>
                {
                    b.HasOne("api_crms.CustomerIdentity.Persistence.Customer", "CandidateCustomer")
                        .WithMany()
                        .HasForeignKey("CandidateCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api_crms.CustomerIdentity.Persistence.SourceReference", "SourceReference")
                        .WithMany("IdentityMatchCandidates")
                        .HasForeignKey("SourceReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateCustomer");

                    b.Navigation("SourceReference");
                });

            modelBuilder.Entity("api_crms.CustomerIdentity.Persistence.SourceReference", b =>
                {
                    b.HasOne("api_crms.CustomerIdentity.Persistence.Customer", "Customer")
                        .WithMany("SourceReferences")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("api_crms.CustomerIdentity.Persistence.Customer", b =>
                {
                    b.Navigation("SourceReferences");
                });

            modelBuilder.Entity("api_crms.CustomerIdentity.Persistence.SourceReference", b =>
                {
                    b.Navigation("IdentityMatchCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
