// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_crms.Data;

#nullable disable

namespace api_crms.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826202255_AddCustomerField")]
    partial class AddCustomerField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("api_crms.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("PlatformCartId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform_cart_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("PlatformCartId")
                        .IsUnique();

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cart_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("cart_item", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<decimal>("LifetimeValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("lifetime_value");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<decimal?>("SentimentScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("sentiment_score");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("custom_field_definition", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomFieldDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_field_definition_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldDefinitionId");

                    b.ToTable("custom_field_option", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bool_value");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<Guid>("CustomFieldDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_field_definition_id");

                    b.Property<DateTimeOffset?>("DateValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_value");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("number_value");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("option_id");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("text_value");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldDefinitionId");

                    b.HasIndex("OptionId");

                    b.HasIndex("ContactId", "CustomFieldDefinitionId")
                        .IsUnique();

                    b.ToTable("custom_field_value", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.IdentityMatchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_contact_id");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("SourceReferenceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_reference_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateContactId");

                    b.HasIndex("SourceReferenceId");

                    b.ToTable("identity_match_candidate", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PlatformOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform_order_id");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("refunded_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("PlatformOrderId")
                        .IsUnique();

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.OrderLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_line_item", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.ProcessedEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId");

                    b.ToTable("processed_event", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("InStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("in_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PlatformProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform_product_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlatformProductId")
                        .IsUnique();

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Rule")
                        .HasColumnType("TEXT")
                        .HasColumnName("rule");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("segment", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.SegmentMembership", b =>
                {
                    b.Property<Guid>("SegmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("segment_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("SegmentId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("segment_membership", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.SourceReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("MatchConfidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("match_confidence");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("SourceSystem", "SourceId")
                        .IsUnique();

                    b.ToTable("source_reference", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.TimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_module");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("ContactId", "OccurredAt");

                    b.ToTable("timeline_entry", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("StopCondition")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_condition");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.ToTable("workflow", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_step_index");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("NextStepDueAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_step_due_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("Status", "NextStepDueAt");

                    b.ToTable("workflow_run", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActionConfig")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_config");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<TimeSpan>("WaitDuration")
                        .HasColumnType("TEXT")
                        .HasColumnName("wait_duration");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("workflow_step", (string)null);
                });

            modelBuilder.Entity("api_crms.Models.Cart", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("Carts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.CartItem", b =>
                {
                    b.HasOne("api_crms.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("api_crms.Models.Contact", b =>
                {
                    b.HasOne("api_crms.Models.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldOption", b =>
                {
                    b.HasOne("api_crms.Models.CustomFieldDefinition", "Definition")
                        .WithMany("Options")
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldValue", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_crms.Models.CustomFieldDefinition", "Definition")
                        .WithMany("Values")
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_crms.Models.CustomFieldOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");

                    b.Navigation("Definition");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("api_crms.Models.IdentityMatchCandidate", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "CandidateContact")
                        .WithMany()
                        .HasForeignKey("CandidateContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api_crms.Models.SourceReference", "SourceReference")
                        .WithMany("IdentityMatchCandidates")
                        .HasForeignKey("SourceReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateContact");

                    b.Navigation("SourceReference");
                });

            modelBuilder.Entity("api_crms.Models.Order", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("Orders")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.OrderLineItem", b =>
                {
                    b.HasOne("api_crms.Models.Order", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("api_crms.Models.SegmentMembership", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_crms.Models.Segment", "Segment")
                        .WithMany("Memberships")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("api_crms.Models.SourceReference", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("SourceReferences")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.TimelineEntry", b =>
                {
                    b.HasOne("api_crms.Models.Contact", "Contact")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("api_crms.Models.WorkflowRun", b =>
                {
                    b.HasOne("api_crms.Models.Workflow", "Workflow")
                        .WithMany("Runs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("api_crms.Models.WorkflowStep", b =>
                {
                    b.HasOne("api_crms.Models.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("api_crms.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("api_crms.Models.Company", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("api_crms.Models.Contact", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("CustomFieldValues");

                    b.Navigation("Orders");

                    b.Navigation("SourceReferences");

                    b.Navigation("TimelineEntries");
                });

            modelBuilder.Entity("api_crms.Models.CustomFieldDefinition", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("api_crms.Models.Order", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("api_crms.Models.Segment", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("api_crms.Models.SourceReference", b =>
                {
                    b.Navigation("IdentityMatchCandidates");
                });

            modelBuilder.Entity("api_crms.Models.Workflow", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
