export * from "./components";
export * from "./services/contacts-api";
export * from "./services/companies-api";
export * from "./services/customers-api";
export * from "./services/ecommerce-api";
export * from "./types/contact";
export * from "./types/company";
export * from "./types/customer";
export * from "./types/ecommerce";
export * from "./hooks/useCustomers";
export * from "./hooks/useCustomer";
export * from "./hooks/useCustomerOrders";
export * from "./hooks/useCustomerMarketingHistory";
export * from "./hooks/useEcommerceSyncStatus";
export { useSegments } from "@/features/segments/hooks/useSegments";
export { segmentsApi } from "@/features/segments/services/segments-api";
export type { SegmentListItem, SegmentCondition, SegmentRule, SegmentMember } from "@/features/segments/types/segment";
